### ISSUE TITLE
Glassfish 7 does not write log to Eclipse Console View

### ISSUE THREAD

**Issue by bvfalcon** [OmniFish-EE/eclipse-plugin-glassfish#2]
**Description**: Starting Glalssfish Server from Eclipse IDE (Servers View) new Console View for Glassfish server is being created, but stays empty: logas are not being displayed in Eclipse IDE

**Affects on**: Glassfish 7.0.0-M8 and later

**Note**: Problem appears with [Glassfish migration to GJULE](https://github.com/eclipse-ee4j/glassfish/pull/24046) and have a change of default log format as a reason.

**Comment by arjantijms** [comment]
Thanks for the report. We'll look into it.

**Comment by kiwipetedev** [comment]
@arjantijms , @dmatej , @bvfalcon , I have Eclipse 2024-12 (4.34.0) and OmniFish tools for Eclipse GlassFish (7.0.1) installed. But still no logging appears in the Console. Can this ticket please be reopened, or advise how to get the update that has already been made? Thanks, Peter.

**Comment by bvfalcon** [comment]
> But still no logging appears in the Console.
What GlassFish version do you use? I have similar error in case of default logging options (file logging.properties in domain/config folder) were changed. Now plugin works only with default logger (levels are allowed to hange)

**Comment by kiwipetedev** [comment]
I have Glassfish version 7.0.15.

**Comment by kiwipetedev** [comment]
@arjantijms , @dmatej , @bvfalcon - my question has still not been answered - "how to get the update that has already been made?".

**Comment by OndroMih** [comment]
Hi @kiwipetedev , I'm not sure what you mean. Just in any case, we released a new version of the Eclipse IDE plugin - 7.0.2. It should contain all the changes that are currently in the master branch.

**Comment by kiwipetedev** [comment]
Hi @OndroMih - thanks for your reply. What I meant was changing the version of Glassfish configured in Eclipse (see Window -> Preferences -> Server -> Runtime Environments). Changing that from version 7.0.15 to 7.0.21 fixed the logging issue. See example output:

2025-02-05T21:06:56.798215+13:00|INFO: Using property file: D:\glassfish7\glassfish\domains\domain1\config\logging.properties
2025-02-05T21:06:56.894108+13:00|INFO: Running GlassFish Version: Eclipse GlassFish 7.0.21 (commit: 8dadcddebd0bb8151d4f82052ca810226c340227)

I've now just updated the OmniFish tools for Eclipse GlassFish from 7.0.1 to 7.0.2 - there's been no noticeable change to logging.
